In [3]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

from pathlib import Path
import numpy as np
from matplotlib import pyplot as plt
from sklearn import metrics
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, SpatialDropout1D, Bidirectional
from tensorflow.keras.callbacks import ModelCheckpoint
import itertools 


In [4]:
corpus = list()
labels = list()

with open(Path('all_benign.txt'), 'r') as f:
  lines = f.read().split('\n')[:-1]
  # print(lines[0][33:])
for line in lines:
  doc = line[33:]
  corpus.append(doc)
  labels.append(0)

with open(Path('all_malware.txt'), 'r') as f:
  lines = f.read().split('\n')[:-1]
  # print(lines[0][33:])
for line in lines:
  doc = line[33:]
  corpus.append(doc)
  labels.append(1)

In [5]:
y = np.array(labels)

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv1 = CountVectorizer()
X1 = cv1.fit_transform(corpus).toarray()
cv2 = CountVectorizer(ngram_range=(2,2))
X2 = cv2.fit_transform(corpus).toarray()
cv3 = CountVectorizer(ngram_range=(3,3))
X3 = cv3.fit_transform(corpus).toarray()

In [16]:
from sklearn.model_selection import train_test_split

X11_train, X11_test, y11_train, y11_test = train_test_split(X1, y, test_size = 0.25, random_state = 0)
X21_train, X21_test, y21_train, y21_test = train_test_split(X2, y, test_size = 0.25, random_state = 0)
X31_train, X31_test, y31_train, y31_test = train_test_split(X3, y, test_size = 0.25, random_state = 0)

In [17]:
v1=np.array(X1).astype(np.float32)
for i in range(len(corpus)):
    s=sum(X1[i])
    v1[i]=((X1[i]/s)*100).astype(np.float32)
    
X12_train, X12_test, y12_train, y12_test = train_test_split(v1, y, test_size = 0.1, random_state = 0)

v2=np.array(X2).astype(np.float32)
for i in range(len(corpus)):
    s=sum(X2[i])
    v2[i]=((X2[i]/s)*100).astype(np.float32)

X22_train, X22_test, y22_train, y22_test = train_test_split(v2, y, test_size = 0.1, random_state = 0)

v3=np.array(X3).astype(np.float32)
for i in range(len(corpus)):
    s=sum(X3[i])
    v3[i]=((X3[i]/s)*100).astype(np.float32)

X32_train, X32_test, y32_train, y32_test = train_test_split(v3, y, test_size = 0.1, random_state = 0)

In [18]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [20]:
print("GB \n")

from sklearn.naive_bayes import GaussianNB
classifierGB11 = GaussianNB()
classifierGB11.fit(X11_train, y11_train)
y11_pred = classifierGB11.predict(X11_test)
cm11 = confusion_matrix(y11_test, y11_pred)
print(cm11)
print(metrics.classification_report(y11_test, y11_pred, digits=4))
print(accuracy_score(y11_test, y11_pred))
print('\n')

classifierGB12 = GaussianNB()
classifierGB12.fit(X12_train, y12_train)
y12_pred = classifierGB12.predict(X12_test)
cm12 = confusion_matrix(y12_test, y12_pred)
print(cm12)
print(metrics.classification_report(y12_test, y12_pred, digits=4))
print(accuracy_score(y12_test, y12_pred))
print('\n')

GB 

[[ 46 307]
 [ 20 327]]
              precision    recall  f1-score   support

           0     0.6970    0.1303    0.2196       353
           1     0.5158    0.9424    0.6667       347

    accuracy                         0.5329       700
   macro avg     0.6064    0.5363    0.4431       700
weighted avg     0.6071    0.5329    0.4412       700

0.5328571428571428


[[341  12]
 [264  83]]
              precision    recall  f1-score   support

           0     0.5636    0.9660    0.7119       353
           1     0.8737    0.2392    0.3756       347

    accuracy                         0.6057       700
   macro avg     0.7187    0.6026    0.5437       700
weighted avg     0.7173    0.6057    0.5452       700

0.6057142857142858


[[ 49 304]
 [ 13 334]]
              precision    recall  f1-score   support

           0     0.7903    0.1388    0.2361       353
           1     0.5235    0.9625    0.6782       347

    accuracy                         0.5471       700
   macro avg

In [ ]:
classifierGB21 = GaussianNB()
classifierGB21.fit(X21_train, y21_train)
y21_pred = classifierGB21.predict(X21_test)
cm21 = confusion_matrix(y21_test, y21_pred)
print(cm21)
print(metrics.classification_report(y21_test, y21_pred, digits=4))
print(accuracy_score(y21_test, y21_pred))
print('\n')

classifierGB22 = GaussianNB()
classifierGB22.fit(X22_train, y22_train)
y22_pred = classifierGB22.predict(X22_test)
cm22 = confusion_matrix(y22_test, y22_pred)
print(cm22)
print(metrics.classification_report(y22_test, y22_pred, digits=4))
print(accuracy_score(y22_test, y22_pred))
print('\n')

In [ ]:
classifierGB31 = GaussianNB()
classifierGB31.fit(X31_train, y31_train)
y31_pred = classifierGB31.predict(X31_test)
cm31 = confusion_matrix(y31_test, y31_pred)
print(cm31)
print(metrics.classification_report(y21_test, y21_pred, digits=4))
print(accuracy_score(y21_test, y21_pred))
print('\n')

classifierGB22 = GaussianNB()
classifierGB22.fit(X22_train, y22_train)
y22_pred = classifierGB22.predict(X22_test)
cm22 = confusion_matrix(y22_test, y22_pred)
print(cm22)
print(metrics.classification_report(y22_test, y22_pred, digits=4))
print(accuracy_score(y22_test, y22_pred))
print('\n')

print("RF \n")

In [ ]:
from sklearn.svm import SVC

In [ ]:
classifiersvc11 = SVC(kernel = 'linear', random_state = 0)
classifiersvc11.fit(X11_train, y11_train)
classifiersvc12= SVC(kernel = 'linear', random_state = 0)
classifiersvc12.fit(X12_train, y12_train)

In [ ]:
classifiersvc21 = SVC(kernel = 'linear', random_state = 0)
classifiersvc21.fit(X21_train, y21_train)
classifiersvc22 = SVC(kernel = 'linear', random_state = 0)
classifiersvc22.fit(X22_train, y22_train)

In [ ]:
classifiersvc31 = SVC(kernel = 'linear', random_state = 0)
classifiersvc31.fit(X31_train, y31_train)
classifiersvc32 = SVC(kernel = 'linear', random_state = 0)
classifiersvc32.fit(X32_train, y32_train)

In [ ]:
ysvc11_pred=classifiersvc11.predict(X11_test)
ysvc12_pred=classifiersvc12.predict(X12_test)

In [ ]:
ysvc21_pred=classifiersvc21.predict(X21_test)
ysvc22_pred=classifiersvc22.predict(X22_test)

In [ ]:
ysvc31_pred=classifiersvc31.predict(X31_test)
ysvc32_pred=classifiersvc32.predict(X32_test)

In [ ]:
cm11 = confusion_matrix(y11_test, ysvc11_pred)
print(cm11)
print(accuracy_score(y11_test, ysvc11_pred))
print('\n')
cm12 = confusion_matrix(y12_test, ysvc12_pred)
print(cm12)
print('\n')
print(accuracy_score(y12_test, ysvc12_pred))

In [ ]:
cm21 = confusion_matrix(y21_test, ysvc21_pred)
print(cm21)
print('\n')
print(accuracy_score(y21_test, ysvc21_pred))
cm22 = confusion_matrix(y22_test, ysvc22_pred)
print(cm22)
print(accuracy_score(y22_test, ysvc22_pred))
print('\n')

In [ ]:
cm31 = confusion_matrix(y31_test, ysvc31_pred)
print(cm31)
print('\n')
print(accuracy_score(y31_test, ysvc31_pred))
cm32 = confusion_matrix(y32_test, ysvc32_pred)
print(cm32)
print(accuracy_score(y32_test, ysvc32_pred))
print('\n')

In [15]:

from sklearn.ensemble import RandomForestClassifier

classifierrf11 = RandomForestClassifier(n_estimators = 150, criterion = 'entropy', random_state = 0)
classifierrf11.fit(X11_train, y11_train)
classifierrf12= RandomForestClassifier(n_estimators = 150, criterion = 'entropy', random_state = 0)
classifierrf12.fit(X12_train, y12_train)

RF 

[[340  13]
 [ 35 312]]
              precision    recall  f1-score   support

           0     0.9067    0.9632    0.9341       353
           1     0.9600    0.8991    0.9286       347

    accuracy                         0.9314       700
   macro avg     0.9333    0.9312    0.9313       700
weighted avg     0.9331    0.9314    0.9313       700

0.9314285714285714


[[340  13]
 [ 32 315]]
              precision    recall  f1-score   support

           0     0.9140    0.9632    0.9379       353
           1     0.9604    0.9078    0.9333       347

    accuracy                         0.9357       700
   macro avg     0.9372    0.9355    0.9356       700
weighted avg     0.9370    0.9357    0.9357       700

0.9357142857142857


[[345   8]
 [ 31 316]]
              precision    recall  f1-score   support

           0     0.9176    0.9773    0.9465       353
           1     0.9753    0.9107    0.9419       347

    accuracy                         0.9443       700
   macro avg

In [ ]:
classifierrf21 = RandomForestClassifier(n_estimators = 150, criterion = 'entropy', random_state = 0)
classifierrf21.fit(X21_train, y21_train)
classifierrf22 = RandomForestClassifier(n_estimators = 150, criterion = 'entropy', random_state = 0)
classifierrf22.fit(X22_train, y22_train)

In [ ]:
classifierrf31 = RandomForestClassifier(n_estimators = 150, criterion = 'entropy', random_state = 0)
classifierrf31.fit(X31_train, y31_train)
classifierrf32 = RandomForestClassifier(n_estimators = 150, criterion = 'entropy', random_state = 0)
classifierrf32.fit(X32_train, y32_train)

In [ ]:
yrf11_pred=classifierrf11.predict(X11_test)
yrf12_pred=classifierrf12.predict(X12_test)
yrf21_pred=classifierrf21.predict(X21_test)
yrf22_pred=classifierrf22.predict(X22_test)
yrf31_pred=classifierrf31.predict(X31_test)
yrf32_pred=classifierrf32.predict(X32_test)

In [ ]:
cm11 = confusion_matrix(y11_test, yrf11_pred)
print(cm11)
print(metrics.classification_report(y11_test, yrf11_pred, digits=4))
print(accuracy_score(y11_test, yrf11_pred))
print('\n')
cm12 = confusion_matrix(y12_test, yrf12_pred)
print(cm12)
print(metrics.classification_report(y12_test, yrf12_pred, digits=4))
print(accuracy_score(y12_test, yrf12_pred))
print('\n')

In [ ]:
cm21 = confusion_matrix(y21_test, yrf21_pred)
print(cm21)
print(metrics.classification_report(y21_test, yrf21_pred, digits=4))
print(accuracy_score(y21_test, yrf21_pred))
print('\n')
cm22 = confusion_matrix(y22_test, yrf22_pred)
print(cm22)
print(metrics.classification_report(y22_test, yrf22_pred, digits=4))
print(accuracy_score(y22_test, yrf22_pred))
print('\n')

In [ ]:
cm31 = confusion_matrix(y31_test, yrf31_pred)
print(cm31)
print(metrics.classification_report(y31_test, yrf31_pred, digits=4))
print(accuracy_score(y31_test, yrf31_pred))
print('\n')
cm32 = confusion_matrix(y32_test, yrf32_pred)
print(cm32)
print(metrics.classification_report(y32_test, yrf32_pred, digits=4))
print(accuracy_score(y32_test, yrf32_pred))
print('\n')

In [27]:
classifiersvm11 = SVC(kernel = 'rbf', random_state = 0)
classifiersvm11.fit(X11_train, y11_train)
classifiersvm12= SVC(kernel = 'rbf', random_state = 0)
classifiersvm12.fit(X12_train, y12_train)

SVM 

[[65 87]
 [34 94]]
              precision    recall  f1-score   support

           0     0.6566    0.4276    0.5179       152
           1     0.5193    0.7344    0.6084       128

    accuracy                         0.5679       280
   macro avg     0.5880    0.5810    0.5632       280
weighted avg     0.5938    0.5679    0.5593       280

0.5678571428571428


[[119  33]
 [ 47  81]]
              precision    recall  f1-score   support

           0     0.7169    0.7829    0.7484       152
           1     0.7105    0.6328    0.6694       128

    accuracy                         0.7143       280
   macro avg     0.7137    0.7079    0.7089       280
weighted avg     0.7140    0.7143    0.7123       280

0.7142857142857143


[[ 64  88]
 [ 14 114]]
              precision    recall  f1-score   support

           0     0.8205    0.4211    0.5565       152
           1     0.5644    0.8906    0.6909       128

    accuracy                         0.6357       280
   macro avg   

In [ ]:
classifiersvm21 = SVC(kernel = 'rbf', random_state = 0)
classifiersvm21.fit(X21_train, y21_train)
classifiersvm22 = SVC(kernel = 'rbf', random_state = 0)
classifiersvm22.fit(X22_train, y22_train)

In [ ]:
classifiersvm31 = SVC(kernel = 'rbf', random_state = 0)
classifiersvm31.fit(X31_train, y31_train)
classifiersvm32 = SVC(kernel = 'rbf', random_state = 0)
classifiersvm32.fit(X32_train, y32_train)

In [ ]:
ysvm11_pred=classifiersvm11.predict(X11_test)
ysvm12_pred=classifiersvm12.predict(X12_test)

In [ ]:
ysvm21_pred=classifiersvm21.predict(X21_test)
ysvm22_pred=classifiersvm22.predict(X22_test)

In [ ]:
ysvm31_pred=classifiersvm31.predict(X31_test)
ysvm32_pred=classifiersvm32.predict(X32_test)

In [ ]:
cm11 = confusion_matrix(y11_test, ysvm11_pred)
print(cm11)
print(metrics.classification_report(y11_test, ysvm11_pred, digits=4))
print(accuracy_score(y11_test, ysvm11_pred))
print('\n')
cm12 = confusion_matrix(y12_test, ysvm12_pred)
print(cm12)
print(metrics.classification_report(y12_test, ysvm12_pred, digits=4))
print(accuracy_score(y12_test, ysvm12_pred))
print('\n')

In [ ]:
cm21 = confusion_matrix(y21_test, ysvm21_pred)
print(cm21)
print(metrics.classification_report(y21_test, ysvm21_pred, digits=4))
print(accuracy_score(y21_test, ysvm21_pred))
print('\n')
cm22 = confusion_matrix(y22_test, ysvm22_pred)
print(cm22)
print(metrics.classification_report(y22_test, ysvm22_pred, digits=4))
print(accuracy_score(y22_test, ysvm22_pred))
print('\n')


In [ ]:
cm31 = confusion_matrix(y31_test, ysvm31_pred)
print(cm31)
print(metrics.classification_report(y31_test, ysvm31_pred, digits=4))
print(accuracy_score(y31_test, ysvm31_pred))
print('\n')
cm32 = confusion_matrix(y32_test, ysvm32_pred)
print(cm32)
print(metrics.classification_report(y32_test, ysvm32_pred, digits=4))
print(accuracy_score(y32_test, ysvm32_pred))
print('\n')


In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
classifierdt11 =DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifierdt11.fit(X11_train, y11_train)
classifierdt12= DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifierdt12.fit(X12_train, y12_train)

In [ ]:
classifierdt21 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifierdt21.fit(X21_train, y21_train)
classifierdt22 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifierdt22.fit(X22_train, y22_train)

In [ ]:
classifierdt31 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifierdt31.fit(X31_train, y31_train)
classifierdt32 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifierdt32.fit(X32_train, y32_train)

In [ ]:
ydt11_pred=classifierdt11.predict(X11_test)
ydt12_pred=classifierdt12.predict(X12_test)

In [ ]:
ydt21_pred=classifierdt21.predict(X21_test)
ydt22_pred=classifierdt22.predict(X22_test)

In [ ]:
ydt31_pred=classifierdt31.predict(X31_test)
ydt32_pred=classifierdt32.predict(X32_test)

In [ ]:
cm11 = confusion_matrix(y11_test, ydt11_pred)
print(cm11)
print(accuracy_score(y11_test, ydt11_pred))
print('\n')
cm12 = confusion_matrix(y12_test, ydt12_pred)
print(cm12)
print(accuracy_score(y12_test, ydt12_pred))
print('\n')

In [ ]:
cm21 = confusion_matrix(y21_test, ydt21_pred)
print(cm21)
print(accuracy_score(y21_test, ydt21_pred))
print('\n')
cm22 = confusion_matrix(y22_test, ydt22_pred)
print(cm22)
print(accuracy_score(y22_test, ydt22_pred))
print('\n')

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
classifierknn11 =KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifierknn11.fit(X11_train, y11_train)
classifierknn12= KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifierknn12.fit(X12_train, y12_train)

In [ ]:
classifierknn21 =KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifierknn21.fit(X21_train, y21_train)
classifierknn22 =KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifierknn22.fit(X22_train, y22_train)

In [ ]:
classifierknn31 =KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifierknn31.fit(X31_train, y31_train)
classifierknn32 =KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifierknn32.fit(X32_train, y32_train)

In [ ]:
yknn11_pred=classifierknn11.predict(X11_test)
yknn12_pred=classifierknn12.predict(X12_test)

In [ ]:
yknn21_pred=classifierknn21.predict(X21_test)
yknn22_pred=classifierknn22.predict(X22_test)

In [ ]:
yknn31_pred=classifierknn31.predict(X31_test)
yknn32_pred=classifierknn32.predict(X32_test)

In [ ]:
cm11 = confusion_matrix(y11_test, yknn11_pred)
print(cm11)
print(accuracy_score(y11_test, yknn11_pred))
print('\n')
cm12 = confusion_matrix(y12_test, yknn12_pred)
print(cm12)
print(accuracy_score(y12_test, yknn12_pred))
print('\n')

In [ ]:
cm21 = confusion_matrix(y21_test, yknn21_pred)
print(cm21)
print(accuracy_score(y21_test, yknn21_pred))
print('\n')
cm22 = confusion_matrix(y22_test, yknn22_pred)
print(cm22)
print(accuracy_score(y22_test, yknn22_pred))
print('\n')

In [ ]:
cm31 = confusion_matrix(y31_test, ydt31_pred)
print(cm31)
print(accuracy_score(y31_test, ydt31_pred))
print('\n')
cm32 = confusion_matrix(y32_test, ydt32_pred)
print(cm32)
print(accuracy_score(y32_test, ydt32_pred))
print('\n')

print("KNN \n")